version: '3.9'
services:
  fastapi-backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - 4000:${BACK_PORT}
    command: sh -c "uvicorn main:app --reload --port=${BACK_PORT} --host=0.0.0.0"
    environment:
      # NODE_ENV: ${NODE_ENV}
      BACK_PORT: ${BACK_PORT}
      FRONT_PORT: ${FRONT_PORT}
      NGINX_PORT: ${NGINX_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - pg-db
    networks:
      - appnet
      - dbnet
  
  react-frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - 5000:${FRONT_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      FRONT_PORT: ${FRONT_PORT}
      BACK_PORT: ${BACK_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - fastapi-backend
    networks:
      - appnet
  
  pg-db:
    build: ./db
    container_name: pg-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 3434:${POSTGRES_PORT}
    networks:
      - dbnet

volumes:
  pg-data:

networks:
  appnet:
    name: appnet
    driver: bridge
  dbnet:
    name: dbnet
    driver: bridge