FROM python:3.11

# Установка зависимостей
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Копирование приложения
COPY . /app

# Открытие порта
EXPOSE ${BACK_PORT}

# Команда для запуска приложения
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "$BACK_PORT"]